name: xzx
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  jackson.serialization.indent_output: true
